### PR TITLE
Support for custom ciphers and protocols for https requests

### PR DESCRIPTION
**Pull request by Hakky54**
This pull request is an implementation for the following feature request: https://github.com/Kong/unirest-java/issues/380

Usage would be for example:
```
Unirest.config()
    .sslContext(sslContext)
    .protocols("TLSv1.2")
    .ciphers("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
```

This will force your client to communicate over TLSv1.2 and TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 with the server or else it will fail. This setup will also prevent your client to communicate with older protocols such as TLSv1.1 and TLSv1

### CODE REVIEW

**Review by ryber — APPROVED** [review]
This looks great. I have a couple other things to work into a release, I'll probably cut it this weekend

**Comment by Hakky54** [comment]
Thank you very much!

**Comment by ryber** [comment]
@Hakky54 there was an issue with the GitHub Actions setup for PRs would you might rebasing your branch with master (or merge master, either way)

**Comment by Hakky54** [comment]
I just merged your master branch with mine master branch and pushed the changes. Please let me know if something else needs to be done

**Review by ryber — APPROVED** [review]

**Comment by ryber** [comment]
This is in 3.11.04

**Pull request merged**
