### PR TITLE
Cookie support

### PR DESCRIPTION
**Pull request by zoltan-tornoczky**
I needed cookie support in my app, so I added it to the lib, pull it if you want to!

### CODE REVIEW

**Comment by BenjaminEHowe** [comment]
It would be really helpful if cookie support was added. I know that ReSTful APIs shouldn't use cookies, but unfortunately some do - such as the APIs behind the online banking interfaces for NewDay (~5.5 million customers) and American Express (~100 million cardmembers). I've found Unirest brilliantly straightforward to use as part of my final year project at university, but unfortunately the lack of cookie support is a big issue for me :disappointed:.

I note that the Unirest libraries for Node.js and PHP support cookies. Is there any chance of changing your mind for Java?

**Comment by stodge** [comment]
What if your REST service requires authentication that uses cookies for storing the session ID and the CSRF token?

**Comment by Jebrone** [comment]
Why doesn't this support Cookies?

**Comment by jonasborn** [comment]
Sorry for reopening this, but basic cookie support ist a quite forward feature. Looking at the current OpenAPI spec. its also defined as a possible auth mechanism. Without this feature, Unirest would not support a huge amount of apis out there.

**Comment by ryber** [comment]
Unirest does now support cookies:
http://kong.github.io/unirest-java/#configuration

**Pull request closed without merging**
