### PR TITLE
Added example for list deserializing

### PR DESCRIPTION
**Pull request by bedware**
Add this example, please. Should save a lot of time to guys like me.

### CODE REVIEW

**Comment by ryber** [comment]
This is one way to do it, or you can actually use the generic type hint like this to do it natively:

```java
List<Book> books = Unirest.get("http://httpbin.org/books/")
				.asObject(new GenericType<List<Book>>(){})
				.getBody();
``` 

This is the example I'd prefer to see added to the doc as it works with all the other chaining mechanism. It can also be used for any generic type, not just collections

**Comment by bedware** [comment]
Have checked right now. It doesn't compile with this error - Cannot resolve method 'stream(java.util.List<model.Address>)'

ex
Any ideas?

In general, I'd prefer the way you suggested but it doesn't work.

**Comment by bedware** [comment]
Sorry, it works as expected. Need to unwrap the Arrays.stream
```java
// Получение адресов
        Map<Long, PreciseModel> modelsMap = Unirest.get("http://localhost:8080/address/")
            .asObject(new GenericType<List<Address>>(){}).getBody().stream()
            .map(this::convertAddressToModel)
            .collect(Collectors.toMap(PreciseModel::getId, item -> item));
```
Going to make new patch.

**Comment by ryber** [comment]
Thanks @bedware!

**Pull request merged**
