### PR TITLE
Add option to set custom CookieSpecs

### PR DESCRIPTION
**Pull request by zhztheplayer**
"Invalid Headers" warning can be found in some use cases. (See [https://github.com/Mashape/unirest-java/issues/97](https://github.com/Mashape/unirest-java/issues/97))

For solving this problem, we can set a custom HttpClient, which was created with a custom CookieSpecs. 

And this fix makes it easy to set a custom CookieSpecs by adding set method to Unirest API.

### CODE REVIEW

**Comment by tnimni** [comment]
can anyone merge this?

**Comment by tnimni** [comment]
can you merge this?

**Comment by tnimni** [comment]
is it possible to approve the pull request and merge?

**Comment by ryber** [comment]
I know it has been a long time since you posted this. This project was kind of mothballed for a long time. But now it's back and being maintained. I maintained a fork for the last two years and It has been merged back into the main project. Most of the classes have been modified in some way or another so merging this is going to take some work.

If you want to do that I'd be happy to work with you on merging this. Or if you have moved on (understandable) I can do it myself but the rebase/merge will probably result in you losing "credit" in the git history as everything has moved around.

**Comment by zhztheplayer** [comment]
@ryber - It's great to hear that the project is back.

I wish to help but currently I'm a little too busy to push this forward. Hopefully you can help and I don't mind not owning the "credit" on git history.

Thank you very much!

**Comment by ryber** [comment]
this is now supported. Thanks for the patience, I'm sorry it could not have been done in a more timely manner

**Pull request closed without merging**
